categories:
  - id: default
    title: narrat.game_menu.achievements.achievements
  - id: secret
    title: narrat.game_menu.achievements.secret_achievements

defaultAchievementIcon: img/achievements/trophy.png

achievements:
  janken:
    name: Janken
    description: Win at Rock paper scissors Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec auctor, nisl eget ultricies tincidunt.
    icon: img/achievements/janken.webp
  win_game:
    name: Won the game
    description: Get this achievement by being a true ultimate pro gamer
    icon: img/items/bread.webp
  find_book:
    name: Bookworm
    description: Find the book in the hidden room
    icon: img/items/bread.webp
  chapter_1:
    name: Chapter 1
    description: Finish chapter 1
    icon: img/items/book.webp
  chapter_2:
    name: Chapter 2
    description: Finish chapter 2
    icon: img/items/book.webp
  secret_achievement:
    name: Secret boss found
    description: Beat the secret boss
    icon: img/items/book.webp
    secret: true
    category: secret

notifyNewAchievements: true

secretAchievements:
  censorDescription: true
  censorName: true
  hideUntilObtained: false
