animations:
  rotate:
    keyframes: rotate
    options:
      duration: 1000
      iterations: 1
  long-screenshake:
    keyframes: narrat-screenshake
    options:
      duration: 150
      iterations: 5

keyframes:
  rotate:
    - transform: rotate(0deg)
    - transform: rotate(360deg)
