buttons:
  shopButton:
    enabled: false
    text: 'Shop'
    cssClass: test-class
    position:
      left: 272
      top: 142
      width: 200
      height: 50
    anchor:
      x: 0.5
      y: 0.5
    action: shopButton
  tester:
    enabled: true
    text: 'Test'
    position:
      left: 400
      top: 300
      width: 200
      height: 50
    action: test_transition
  parkButton:
    enabled: false
    text: Park
    position:
      left: 682
      top: 462
      width: 200
      height: 50
    anchor:
      x: 0.5
      y: 0.5
    action: parkButton
clickableDuringScriptsByDefault: false
