export { getCommonConfig as getConfig } from '../config';
export type { Config } from '../config/config-output';
export * from '../config/config-input';
export {
  animationsConfig,
  audioConfig,
  buttonsConfig,
  charactersConfig,
  choicesConfig,
  fontsConfig,
  getAssetUrl,
  getAchievementConfig,
  getButtonConfig,
  getCommonConfig,
  getChoicePromptConfig,
  getDataUrl,
  getImageUrl,
  getItemConfig,
  getLocalizationConfig,
  getHudStatConfig,
  getObjectiveConfig,
  getQuestConfig,
  getScreenConfig,
  getSkillConfig,
  getSkillCheckConfig,
  getSplitConfigUrl,
  getTooltipConfig,
  itemsConfig,
  questsConfig,
  screensConfig,
  skillsConfig,
  skillChecksConfig,
  tooltipsConfig,
} from '../config';
