files:
  game:
    src: music/music.mp3
    loop: true
  battle:
    src: music/battle.mp3
    loop: true
  click:
    src: audio/click.ogg
  game_start:
    src: audio/game_start.ogg
  failure:
    src: audio/failure.ogg
  success:
    src: audio/success.wav
options:
  volume: 0.5
  musicFadeInTime: 0.5
  musicFadeInDelay: 0.5
  musicFadeOutTime: 0.5
audioTriggers:
  onPlayerAnswered: click
  onPressStart: game_start
  onSkillCheckFailure: failure
  onSkillCheckSuccess: success
