skills:
  strength:
    name: Strength
    description: Increases your attack power.
    startingLevel: 1
    icon: img/skills/agility.webp
  intelligence:
    name: Intelligence
    description: Increases your magic power.
    startingLevel: 1
    icon: img/skills/logic.webp
  agility:
    name: Agility
    description: How good you are at moving around.
    startingLevel: 1
    icon: img/skills/agility.webp
